// Tailwind-only styling adapter preserves original component logic and test selectors.
const styles = {
  page: 'container max-w-full px-4 py-6 sm:px-6 lg:px-8 lg:py-8 min-w-0', 'page-actions': 'flex w-full flex-wrap items-center gap-2 sm:w-auto [&>button]:flex-1 sm:[&>button]:flex-none [&>a]:flex-1 sm:[&>a]:flex-none',
  toolbar: 'flex flex-col items-stretch justify-between gap-3 mb-5 sm:flex-row sm:items-center', filters: 'gap-3',
  search: 'relative flex min-w-0 items-center gap-2 rounded-lg border border-border bg-card px-3 w-full sm:w-80 [&>svg]:shrink-0 [&>svg]:text-muted-foreground [&>input]:min-w-0 [&>input]:border-0 [&>input]:bg-transparent [&>input]:shadow-none [&>input]:focus:ring-0',
  'result-count': 'text-xs text-muted-foreground', loading: 'p-16 text-center text-sm text-muted-foreground animate-pulse',
  empty: 'flex flex-col items-center justify-center gap-3 rounded-lg border border-dashed border-border bg-card p-8 text-center text-muted-foreground sm:p-16 [&_h3]:font-medium [&_h3]:text-foreground', compact: '!p-7',
  'table-wrap': 'max-w-full overflow-x-auto rounded-xl border border-border bg-card',
  'responsive-table': 'min-w-[760px] w-full text-left text-sm [&_th]:bg-muted/50 [&_th]:px-4 [&_th]:py-3.5 [&_th]:text-[11px] [&_th]:font-semibold [&_th]:uppercase [&_th]:tracking-wider [&_th]:text-muted-foreground sm:[&_th]:px-5 [&_td]:px-4 [&_td]:py-4 sm:[&_td]:px-5 [&_tbody_tr]:border-t [&_tbody_tr]:border-border [&_td]:align-top [&_td]:whitespace-nowrap',
  'clickable-rows': '[&_tbody_tr]:cursor-pointer [&_tbody_tr]:transition-colors [&_tbody_tr:hover]:bg-muted/50 [&_tbody_tr:focus-visible]:bg-secondary',
  'order-number': 'font-semibold text-primary', 'party-cell': 'font-medium', remarks: 'max-w-64 truncate text-muted-foreground',
  pagination: 'mt-5 flex flex-col items-stretch justify-between gap-3 text-xs text-muted-foreground sm:flex-row sm:items-center [&>button]:justify-center',
  status: 'inline-flex w-fit items-center rounded-md bg-amber-50 px-2 py-1 text-[11px] font-medium text-amber-700', sent: '!bg-emerald-50 !text-emerald-700',
  'error-banner': 'my-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700', 'field-error': 'mt-1 text-xs text-red-600',
  notice: 'my-3 rounded-lg bg-secondary p-3 text-sm text-primary', 'modal-alert': 'rounded-lg bg-red-50 p-3 text-red-700',
  'icon-button': 'inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-muted-foreground hover:bg-muted disabled:opacity-40', 'danger-icon': 'hover:text-red-600',
  'back-link': 'mb-5 inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-primary',
  'summary-grid': 'mb-6 grid gap-4 grid-cols-1 sm:grid-cols-2 xl:grid-cols-4', 'summary-stat': 'rounded-xl border border-border bg-card p-5 [&>span]:text-xs [&>span]:text-muted-foreground [&>strong]:block [&>strong]:mt-3 [&>strong]:break-words [&>strong]:text-2xl [&>strong]:font-semibold',
  'challan-summary': 'sm:!grid-cols-2', 'stock-summary': 'mb-6', 'team-summary': 'sm:!grid-cols-3',
  'editor-fieldset': 'min-w-0 border-0 p-0 disabled:opacity-70', 'order-editor-basics': 'grid gap-4 md:grid-cols-3 rounded-xl border bg-card p-5 mb-4',
  'party-meta': 'mb-4 flex flex-wrap gap-4 text-xs text-muted-foreground', 'parcel-editor': 'mb-5 min-w-0 rounded-xl border border-border bg-card p-4 sm:p-5',
  'parcel-head': 'flex flex-col gap-4 mb-5 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between', 'parcel-kicker': 'text-[10px] font-semibold uppercase tracking-[0.15em] text-muted-foreground',
  'target-field': 'flex w-full items-end gap-3 sm:w-auto [&_label]:flex-1 sm:[&_label]:flex-none [&_input]:max-w-none sm:[&_input]:max-w-32', 'comp-header': 'hidden md:grid md:grid-cols-[2fr_1.5fr_1fr_1fr_1fr_32px] gap-3 text-[10px] uppercase text-muted-foreground mb-2',
  'comp-row': 'grid grid-cols-1 gap-3 rounded-lg border border-border/60 p-3 mb-3 sm:grid-cols-2 md:grid-cols-[2fr_1.5fr_1fr_1fr_1fr_32px] md:border-0 md:p-0 md:items-center', 'auto-value': 'text-sm text-muted-foreground', 'row-total': 'font-semibold',
  'add-row': 'inline-flex items-center gap-2 text-xs font-medium text-primary py-2', 'add-inline': 'mb-3 inline-flex items-center gap-2 text-sm text-primary',
  'parcel-total': 'mt-4 flex flex-col gap-3 rounded-lg bg-muted p-4 sm:flex-row sm:items-center sm:justify-between [&_strong]:block [&_strong]:break-words [&_strong]:text-lg [&_small]:text-xs [&_small]:font-normal [&_span]:text-xs',
  complete: '!bg-emerald-50 text-emerald-700', over: '!bg-red-50 text-red-700', 'parcel-state': 'flex items-center gap-2 text-xs font-medium',
  'details-status': 'mb-6 flex items-center gap-4 text-sm', 'details-grid': 'grid gap-5 xl:grid-cols-2', 'detail-parcel': 'rounded-xl border bg-card p-5',
  'detail-parcel-head': 'flex flex-col gap-2 mb-5 sm:flex-row sm:items-center sm:justify-between [&_h2]:text-xl [&_h2]:font-semibold', 'detail-rows': 'divide-y',
  'detail-row': 'flex flex-col justify-between gap-1 py-3 text-sm sm:flex-row sm:gap-3', 'detail-total': 'mt-4 flex flex-col justify-between gap-2 border-t pt-4 text-sm sm:flex-row sm:items-center',
  'challan-strip': 'mt-4 flex flex-col gap-2 rounded-lg bg-secondary p-3 text-xs', 'row-open': 'inline-flex items-center gap-1 text-xs text-primary',
  'challan-contents': 'text-xs', 'modal-scrim': 'fixed inset-0 z-50 flex items-center justify-center bg-foreground/35 p-4 backdrop-blur-sm',
  'modal-backdrop': 'fixed inset-0 z-50 flex items-center justify-center bg-foreground/35 p-4 backdrop-blur-sm',
  'modal-card': 'w-full max-w-lg max-h-[90vh] overflow-y-auto rounded-xl bg-card shadow-xl', 'stock-modal': '!max-w-2xl',
  modal: 'w-full max-w-lg rounded-xl bg-card p-6 shadow-xl', 'modal-head': 'flex items-center justify-between gap-3 border-b p-5 [&_h2]:font-semibold [&_h2]:text-lg',
  'modal-body': 'space-y-4 p-4 sm:p-5', 'modal-foot': 'flex flex-col-reverse justify-end gap-2 border-t p-4 sm:flex-row', 'modal-hint': 'text-xs text-muted-foreground',
  'stock-form-grid': 'grid gap-4 md:grid-cols-2 !space-y-0', 'span-2': 'md:col-span-2',
  'list-head': 'flex flex-col gap-2 mb-4 sm:flex-row sm:items-center sm:justify-between sm:gap-3 [&_h2]:font-semibold [&>span]:text-xs [&>span]:text-muted-foreground',
  'master-layout': 'grid gap-6 lg:grid-cols-[320px_1fr]', 'master-add': 'rounded-xl border bg-card p-5 h-fit [&_h2]:font-semibold [&_p]:text-sm [&_p]:text-muted-foreground [&_p]:my-3',
  'master-list': 'rounded-xl border bg-card p-4 sm:p-5', 'master-item': 'border-t py-4 cursor-pointer [&>div:first-child]:flex [&>div:first-child]:flex-col [&>div:first-child]:gap-3 sm:[&>div:first-child]:flex-row sm:[&>div:first-child]:items-center sm:[&>div:first-child]:justify-between',
  'master-main': 'flex flex-col gap-1 text-sm [&>span]:text-xs [&>span]:text-muted-foreground', 'master-actions': 'flex gap-1', 'input-action': 'flex items-center gap-2',
  'party-master-form': 'space-y-4', 'volume-panel': 'mt-4 rounded-lg bg-muted/60 p-4', 'volume-list': 'flex flex-wrap gap-2 mb-3 [&>span]:inline-flex [&>span]:items-center [&>span]:gap-2 [&>span]:rounded-md [&>span]:border [&>span]:bg-card [&>span]:p-2 [&>span]:text-xs',
  'volume-add': 'grid gap-2 sm:grid-cols-[1fr_80px_auto]', 'bulk-input-section': 'rounded-xl border bg-card p-4 sm:p-6', 'section-label': 'mb-5 flex items-start gap-3 [&>span]:flex [&>span]:size-9 [&>span]:shrink-0 [&>span]:items-center [&>span]:justify-center [&>span]:rounded-lg [&>span]:bg-secondary [&>span]:text-primary [&>span]:text-xs [&_h2]:font-semibold [&_p]:text-xs [&_p]:text-muted-foreground',
  'bulk-blocks': 'space-y-5', 'bulk-block': 'rounded-lg border p-4 space-y-4 sm:p-5', 'bulk-block-head': 'flex items-center justify-between', 'bulk-parcel-builder': 'rounded-lg bg-muted/50 p-3 space-y-3 sm:p-4',
  'bulk-picker-grid': 'grid items-end gap-3 md:grid-cols-[1fr_1fr_auto]', 'bulk-picker-quantity': 'grid items-end gap-3 md:grid-cols-[1fr_1fr_auto]',
  'bulk-mixed-items': 'flex flex-wrap gap-2 [&>span]:inline-flex [&>span]:items-center [&>span]:gap-2 [&>span]:rounded-md [&>span]:bg-secondary [&>span]:pl-3 [&>span]:text-xs',
  'bulk-input-footer': 'mt-5 flex flex-col items-stretch justify-between gap-4 sm:flex-row sm:flex-wrap sm:items-center', 'bulk-hints': 'text-xs text-muted-foreground', 'bulk-input-actions': 'flex flex-col gap-2 sm:flex-row sm:flex-wrap',
  'bulk-preview-section': 'mt-7', 'bulk-order': 'mb-4 rounded-xl border bg-card p-4 sm:p-5', 'bulk-order-head': 'flex items-start justify-between gap-3 mb-4',
  'bulk-order-toggle': 'flex flex-wrap items-center gap-3 text-sm text-left', 'bulk-save-footer': 'flex flex-col justify-between gap-3 mt-5 sm:flex-row',
  'bulk-success': 'mb-5 flex gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-800 [&_h2]:font-semibold', 'receipt-links': 'mt-2 flex flex-wrap gap-3 text-xs [&_a]:inline-flex [&_a]:items-center [&_a]:gap-1',
  'parse-error': 'mt-2 flex flex-col gap-1 text-xs', 'suggestions-panel': 'rounded-xl border bg-card p-5 mb-6', 'suggestion-grid': 'grid gap-3 lg:grid-cols-3',
  'suggestion-card': 'rounded-lg border p-4 space-y-3 [&_h3]:font-semibold [&_p]:text-xs [&_p]:text-muted-foreground [&>strong]:block', ready: 'bg-emerald-50/50', partial: 'bg-amber-50/50',
  'stock-batches': 'mt-6 rounded-xl border bg-card p-4 sm:p-5', 'stock-short': 'text-amber-700', 'stock-ok': 'text-emerald-700',
  'movement-list': 'divide-y [&>div]:flex [&>div]:flex-col [&>div]:gap-1 [&>div]:py-3 [&_strong]:text-sm [&_span]:text-xs [&_span]:text-muted-foreground',
  'urgent-panel': 'mb-6 rounded-xl border bg-card p-4 sm:p-5', 'urgent-form': 'grid gap-3 md:grid-cols-[2fr_1fr_1fr_auto] mb-4', 'urgent-item': 'flex flex-col gap-3 border-t py-3 sm:flex-row sm:items-center sm:justify-between [&_strong]:block [&_span]:text-xs [&_span]:text-muted-foreground',
  'batch-grid': 'grid gap-4 xl:grid-cols-2', 'batch-card': 'rounded-xl border p-4 sm:p-5', 'batch-head': 'flex flex-col gap-3 sm:flex-row sm:justify-between [&_h3]:break-words [&_h3]:font-semibold [&_h3]:text-lg [&_p]:text-xs [&_p]:text-muted-foreground',
  'stage-strip': 'flex flex-wrap gap-2 my-4 [&>span]:flex [&>span]:gap-3 [&>span]:rounded-md [&>span]:bg-muted [&>span]:px-3 [&>span]:py-2 [&>span]:text-xs',
  'batch-actions': 'flex flex-col gap-2 mt-4 sm:flex-row sm:flex-wrap', 'file-control': 'mt-2 flex items-center gap-2 rounded-md border p-2 [&_input]:border-0 [&_input]:p-0 [&_input]:text-xs',
  'design-photo': 'max-h-80 w-full object-contain rounded-lg', 'edit-stage-row': 'grid grid-cols-[1fr_88px_32px] gap-2 mb-3 sm:grid-cols-[1fr_120px_32px]',
  'stage-total': 'flex flex-col gap-1 text-xs rounded-lg p-3 sm:flex-row sm:justify-between', ok: 'bg-emerald-50 text-emerald-700', bad: 'bg-red-50 text-red-700',
  'team-create': 'rounded-xl border bg-card p-4 sm:p-5 [&_h2]:font-semibold mb-6', 'team-form': 'grid gap-4 md:grid-cols-3 mt-4', 'team-access-picker': 'md:col-span-3 text-xs space-y-3',
  'access-grid': 'grid gap-2 sm:grid-cols-2 lg:grid-cols-4', 'access-check': '!flex !flex-row items-center gap-2 !space-y-0 [&>input]:!w-4 [&>input]:!h-4 [&>input]:accent-primary',
  'team-filter': 'flex flex-wrap gap-2 mb-4 [&>button]:px-4 [&>button]:py-2 [&>button]:rounded-lg [&>button]:text-xs [&>button]:border',
  active: 'bg-secondary text-primary', 'team-member': 'grid grid-cols-[40px_1fr] items-center gap-4 rounded-xl border bg-card p-4 mb-3 sm:grid-cols-[40px_1fr_auto] sm:p-5',
  'team-avatar': 'flex size-10 items-center justify-center rounded-lg bg-secondary text-primary', 'team-identity': 'flex flex-col gap-1 text-sm [&>span]:text-xs [&>span]:text-muted-foreground',
  'team-actions': 'col-span-full flex flex-wrap items-center gap-2 sm:col-auto', 'member-access': 'col-span-full',
  'export-dropdown': 'relative', 'export-menu': 'absolute right-0 top-full z-20 mt-2 w-[min(18rem,calc(100vw-2rem))] rounded-xl border bg-card p-1.5 shadow-lg',
  'export-menu-item': 'w-full rounded-lg p-3 text-left hover:bg-muted [&_strong]:block [&_strong]:text-xs [&_span]:block [&_span]:text-[11px] [&_span]:text-muted-foreground [&_span]:mt-1',
};
export const workspaceClasses = value => String(value || '').split(/\s+/).map(token => styles[token] || token).join(' ');
