'use client';
import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, Layers3, ShieldCheck, Package, ReceiptText, Factory, Check } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { errorText } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const App = () => {
  const { login } = useAuth();
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [show, setShow] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { await login(email, password); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  return <main className="grid min-h-screen bg-card lg:grid-cols-[1.05fr_1fr]">
    <section className="relative hidden flex-col justify-between overflow-hidden bg-sidebar p-12 lg:flex xl:p-16"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Layers3 size={23}/></span><span className="text-xl font-semibold tracking-tight">aditya prints<span className="text-primary">.</span></span></div>
      <div className="relative z-10 max-w-lg py-12"><p className="mb-5 text-[10px] font-semibold tracking-[0.22em] text-primary">YOUR FACTORY. IN SYNC.</p><h1 className="text-5xl font-semibold leading-[1.15] tracking-[-0.04em] xl:text-[58px]">Good work starts<br/>with a clear view.</h1><p className="mt-6 max-w-sm text-base leading-7 text-muted-foreground">Orders, production, and every rupee accounted for. A little more clarity for your everyday.</p>
      <div className="mt-10 max-w-sm rounded-2xl border border-border bg-card p-5 shadow-[0_8px_35px_-20px_rgba(0,0,0,0.2)]"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-semibold">Your connected workspace</span><span className="flex items-center gap-1 text-[9px] text-primary"><span className="size-1 rounded-full bg-primary"/>ALL IN ONE</span></div>{[[Package, 'Orders & dispatch', 'From entry to delivery'], [Factory, 'Production & stock', 'Know what’s ready, and what’s next'], [ReceiptText, 'Bills & cash', 'Clear balances. No guesswork.']].map(([Icon, title, sub]) => <div key={title} className="flex items-center gap-3 border-t border-border py-3.5 last:pb-0"><span className="flex size-9 items-center justify-center rounded-lg bg-secondary text-primary"><Icon size={18}/></span><div className="flex-1"><p className="text-xs font-medium">{title}</p><p className="mt-1 text-[10px] text-muted-foreground">{sub}</p></div><Check size={14} className="text-primary"/></div>)}</div></div>
      <p className="text-[10px] tracking-wide text-muted-foreground">ADITYA PRINTS / BUILT FOR THE EVERYDAY</p><div className="pointer-events-none absolute -bottom-40 -right-48 size-[600px] rounded-full border-[80px] border-primary/[0.025]"/>
    </section>
    <section className="flex flex-col justify-between p-7 md:p-12"><div className="flex items-center justify-end gap-2 text-[11px] text-muted-foreground"><ShieldCheck size={14}/>Private team workspace</div><div className="mx-auto w-full max-w-[370px] py-16"><div className="mb-7 flex size-12 items-center justify-center rounded-xl border border-border text-primary"><Layers3 size={24}/></div><p className="mb-2 text-[10px] font-semibold tracking-[0.16em] text-primary">WELCOME TO YOUR ORDER DESK</p><h2 className="text-3xl font-semibold tracking-tight" data-testid="login-heading">Welcome back.</h2><p className="mt-3 text-sm text-muted-foreground">Sign in to pick up where you left off.</p><form className="mt-8 space-y-5" onSubmit={submit}>{error && <div role="alert" className="rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</div>}<div className="space-y-2"><label htmlFor="email" className="text-xs font-medium">Email address</label><Input id="email" data-testid="login-email-input" type="email" placeholder="you@company.com" autoComplete="username" required value={email} onChange={e => setEmail(e.target.value)} className="h-11 shadow-none"/></div><div className="space-y-2"><label htmlFor="password" className="text-xs font-medium">Password</label><div className="relative"><Input id="password" data-testid="login-password-input" type={show ? 'text' : 'password'} placeholder="Enter your password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)} className="h-11 pr-10 shadow-none"/><button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(!show)} className="absolute right-3 top-3.5 text-muted-foreground">{show ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></div><Button data-testid="login-submit-button" className="h-11 w-full gap-2" disabled={busy}>{busy ? 'Signing in…' : 'Sign in to workspace'}<ArrowRight size={16}/></Button></form><p className="mt-6 text-center text-[11px] leading-5 text-muted-foreground">Need access or help signing in?<br/>Please contact your workspace administrator.</p></div><p className="text-center text-[10px] text-muted-foreground">Aditya Prints · Factory operations, thoughtfully organized.</p></section>
  </main>;
};
export default App;
